version: '3.8'

services:

  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pdfreader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password